'use strict';

// Description: Event pool for socket.io events
const Events = require('events');
const eventEmitter = new Events();

const eventPool = {
  DISCONNECT: 'DISCONNECT',
  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME',
  NEW_GAME: 'NEW_GAME',

  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  PLAYER_SEARCH: 'PLAYER_SEARCH',

  USER_JOIN: 'USER_JOIN',
  USER_LEAVE: 'USER_LEAVE',
  SEND_MESSAGE: 'SEND_MESSAGE',

  CHARACTER_JOIN: 'CHARACTER_JOIN',
  CHARACTER_LEAVE: 'CHARACTER_LEAVE',
  CHARACTER_LEVELED_UP: 'CHARACTER_LEVELED_UP',
  CHARACTER_DEFEATED: 'CHARACTER_DEFEATED',
  CHARACTER_VICTORY: 'CHARACTER_VICTORY',
  CHARACTER_INVENTORY: 'CHARACTER_INVENTORY',

  ENEMY_SPAWN: 'ENEMY_SPAWN',
  ENEMY_KILLED: 'ENEMY_KILLED',
  LOOT_DROP: 'LOOT_DROP',

  USER_JOIN_ERROR: 'USER_JOIN_ERROR',
  USER_LEAVE_ERROR: 'USER_LEAVE_ERROR',
  SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',
};


module.exports = {
  eventPool,
  eventEmitter,
};
